### ISSUE TITLE
Save log to Amazon cloudwatch

### ISSUE THREAD

**Issue by two-for-five** [EarthEvil/yellowHughRichard#76]
step 2

**Comment by tongmingleee** [comment]
https://www.npmjs.com/package/winston-cloudwatch

**Comment by tongmingleee** [comment]
http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_GettingStarted.html

**Comment by tongmingleee** [comment]
Done baby
we all logs are stream to Amazon Cloudwatch. 
Next we need decide what to log
